[workspace]
resolver = "2"
members = [
  "crates/core",
  "crates/plato",
  "crates/emulator",
  "crates/harness",
  "crates/importer",
  "crates/fetcher",
  "crates/foldersync",
  "crates/net",
  "crates/article",
  "crates/pairing",
  "crates/platonic",
  "crates/platonic-recv",
]

[profile.release-minsized]
inherits = "release"
panic = "abort"
codegen-units = 1
opt-level = "z"
lto = true
strip = true
